"""Generate `docs/example_briefing.md` — exactly what an AI assistant sees.

We take the scripted `--demo` recording at the moment the detector stalls and
render two briefings from it: the whole-system briefing and the focused
`get_node_briefing("/detector")` (which adds the pipeline path with the rate
*and* callback bottleneck). The output is deterministic, so a test pins the
committed doc to this generator — regenerate with:

    python -m ros_graph_debugger.examples.sample_briefing
"""

from __future__ import annotations

import os

from ..markdown import snapshot_to_markdown
from ..replay import build_demo_recording

_STALLED_FRAME = 18  # inside the detector bottleneck window (12 <= i < 26)

_HEADER = (
    '<!-- Generated by `python -m ros_graph_debugger.examples.sample_briefing`. '
    'Do not edit by hand. -->\n'
    '# Example: what an AI sees\n\n'
    'The exact Markdown an AI assistant pulls from a running agent (via '
    '`GET /api/v1/snapshot.md`, the `get_runtime_briefing` MCP tool, or '
    '`rgd markdown`). This sample is rendered from the no-ROS `rgd serve '
    '--demo` recording at the moment the `detector` stalls, so it shows the '
    'bottleneck, the stale TF, the slow callback, and the focused pipeline '
    'path. Regenerate with `python -m ros_graph_debugger.examples.sample_briefing`.\n'
)


def build_sample_briefing() -> str:
    _, snaps = build_demo_recording()
    frame = snaps[_STALLED_FRAME]
    full = snapshot_to_markdown(frame)
    focused = snapshot_to_markdown(frame, focus='/detector')
    return (
        f'{_HEADER}\n'
        '## Whole-system briefing\n\n'
        '`GET /api/v1/snapshot.md`\n\n'
        f'{full}\n\n'
        '---\n\n'
        '## Focused briefing on one node\n\n'
        '`GET /api/v1/snapshot.md?focus=/detector` · '
        'MCP `get_node_briefing("/detector")`\n\n'
        f'{focused}\n'
    )


def _doc_path() -> str:
    here = os.path.dirname(__file__)
    return os.path.normpath(os.path.join(here, '..', '..', 'docs',
                                         'example_briefing.md'))


def main() -> None:
    path = _doc_path()
    with open(path, 'w') as f:
        f.write(build_sample_briefing())
    print(f'wrote {path}')


if __name__ == '__main__':
    main()
